name: PR Title Check

on:
  pull_request:
    types: [opened, edited]

jobs:
  validate-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title
        id: check_title
        run: |
          prefixes="build:|chore:|docs:|feat:|fix:|perf:|refactor:|revert:|style:|test:"
          if [[ ! "${{ github.event.pull_request.title }}" =~ ^($prefixes) ]]; then
            echo "::error::PR title must start with one of the following prefixes: build:, chore:, docs:, feat:, fix:, perf:, refactor:, revert:, style:, test:"
            exit 1
          fi